title: "Vibav Srinivasan"
email: "svibavbiz@gmail.com"
description: >-
  Mechanical Design & Mechatronics Engineer | BITS Pilani | CAD | Simulation | Robotics

linkedin_username: vibav-srinivasan-191239221
github_username: vs747

minimal_mistakes_skin:dark
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Kolkata

include:
  - _pages
  - _projects
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Vibav Srinivasan"
  avatar : "/assets/images/vibav.jpg"  # Change once image is uploaded
  bio    : "Mechanical Design | CAD | Mechatronics | Simulation | BITS Pilani"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/vibav-srinivasan-191239221"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vs747"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:svibavbiz@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/vibav-srinivasan-191239221"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vs747"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:svibavbiz@gmail.com"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
collections:
  projects:
    output: true
    permalink: /projects/:name/
